wandb_version: 1

# Example variables below. Uncomment (remove leading '# ') to use them, or just
# delete and create your own.

epochs:
  desc: Number of epochs to train over
  value: 10
batch_size:
  desc: Size of each mini-batch
  value: 32
