wandb_version: 1

# Example variables below. Uncomment (remove leading '# ') to use them, or just
# delete and create your own.

# epochs:
#   desc: Number of epochs to train over
#   value: 100
# batch_size:
#   desc: Size of each mini-batch
#   value: 32

max_words:
    desc: Maximum number of words to work with in dataset
    value: 10000
max_sequence_length:
    desc: Maximum number of words in a document
    value: 50
validation_split:
    desc: Validation split
    value: 0.1
batch_size:
    desc: Size of mini-batch
    value: 128
epochs:
    desc: Number of epochs
    value: 20
